# Generated by Django 5.0.7 on 2024-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racketflight',
            name='flight_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
