# Generated by Django 5.0.7 on 2024-07-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangar', '0003_remove_order_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('racket_flight', 'racket_number', 'order')},
        ),
    ]
